### PR TITLE
Fix special characters in branch name to avoid path error

### PR DESCRIPTION
**Pull request by realjck**
## Pull request type

Please check the type of change your PR introduces:

- [X] Bugfix

## What is the current behavior?

- When a branch name contains a slash, it generates an error when saving the archive

Issue Number: #1

## What is the new behavior?

- Special characters in branch names (<, >, | and /) are replaced by a hyphen (-) for archive naming

### CODE REVIEW

**Comment by michaelmsonne** [comment]
I see I should remove a task so it not will be closed automaticly..

Will fix 👍

**Comment by realjck** [comment]
For the fix I also added other cases for special characters other than the slash and authorized by git (brackets and pipe <> | ).
Please let me know if I need to take another action.

**Comment by realjck** [comment]
Furthermore, in the code, I chose to create a new variable `branchNameFormatted` to increase readability.
The name may of course be changed, or perhaps there is a more elegant fix.

**Comment by michaelmsonne** [comment]
Nice @realjck - I have pushed the code changes and I right now looking at the other to 👍 
For now the code works, but can be I optimize it later :)

**Pull request closed without merging**
